---
apiVersion: v1
kind: ReplicationController
metadata:
  name: goon-ldap
  labels:
    app: goon-ldap
    spec: v1
spec:
  replicas: 1
  selector:
    app: goon-ldap
    spec: v1
  template:
    metadata:
      labels:
        app: goon-ldap
        spec: v1
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/slapd
          imagePullPolicy: Always
          name: goon-ldap
          ports:
            - containerPort: 389
          volumeMounts:
            - name: slapd-storage
              mountPath: /var/lib/openldap/openldap-data
      volumes:
        - name: slapd-storage
          gcePersistentDisk:
            pdName: slapd-storage
            fsType: ext4
