use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :goon_auth, GoonAuth.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [port: 80],
  static_url: [scheme: "https", host: "auth.tendollarbond.com"]

# Do start Phoenix
config :phoenix, :serve_endpoints, true

# Do not print debug messages in production
config :logger, level: :info

# Load secrets from static path
config :goon_auth, secrets_path: "/etc/goon_auth/secrets.json"

# LDAP server is discoverable through Kubernetes DNS
config :goon_auth, :ldap,
  port: 389,
  host: 'goon-ldap',
  admin_dn: 'cn=admin,dc=tendollarbond,dc=com'
